### PR TITLE
Updating dev branch with reverted changes from master because I'm dumb

### PR DESCRIPTION
**Pull request by kstarrmitche**

### CODE REVIEW

**Comment by perrywarner** [comment]
thk u 4 emails dood

u want me 2 do da reviews for u

**Comment by kstarrmitche** [comment]
Yes pleez

**Review by perrywarner — APPROVED** [review]
i make u a review yes

**Comment by perrywarner** [comment]
k i did it u need me 4 anything else? ur giving me lotsa spam with these slack notifs and emails lol

**Pull request merged**
